export 'ability.dart';
export 'flavor_text.dart';
export 'language.dart';
export 'move.dart';
export 'pokemon.dart';
export 'pokemon_specie.dart';
export 'resource.dart';
export 'item.dart';
export 'type.dart';
