name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  # deploy to branch gh-pages
  deploy:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy to branch gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "no-reply@pokemonle.com"

          git clone --branch gh-pages --depth 1 $REPO_URL gh-pages

          cd gh-pages
          git rm -rf .
          cp -r ../build/web/* .

          git add .
          git commit -m "Deploy web: ${{ github.sha }}"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPO_URL: "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
